# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=4000)),
                ('txtname', models.CharField(max_length=200)),
                ('pic', models.CharField(max_length=1000)),
                ('wzurl', models.CharField(max_length=200)),
                ('fn', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=200)),
                ('keynum', models.IntegerField()),
                ('origin', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.IntegerField()),
                ('creator', models.CharField(max_length=45)),
                ('introduce', models.CharField(max_length=2000)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('own_tag', models.CharField(max_length=45)),
                ('permission', models.CharField(max_length=4)),
                ('share_num', models.IntegerField()),
                ('agree_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('friendname', models.CharField(max_length=45)),
                ('tag', models.CharField(max_length=45)),
                ('origin', models.CharField(max_length=200)),
                ('beizhu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.CharField(max_length=100)),
                ('authorgroupid', models.IntegerField()),
                ('groupname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotwords', models.CharField(max_length=200)),
                ('view', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=45)),
                ('picname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=200)),
                ('picurl', models.CharField(max_length=200)),
                ('hosturl', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=1000)),
                ('loadway', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('moditime', models.DateTimeField(auto_now=True)),
                ('keywords', models.CharField(max_length=1000)),
                ('check', models.BooleanField(default=False)),
                ('view', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('abid', models.CharField(max_length=45)),
                ('checkauthor', models.CharField(max_length=100)),
                ('checkwords', models.CharField(max_length=2000)),
                ('rank', models.CharField(max_length=4)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Imgcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abid', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('anwser', models.CharField(max_length=2000)),
                ('agree', models.IntegerField()),
                ('prior', models.IntegerField()),
                ('answertime', models.DateTimeField(auto_now_add=True)),
                ('nameid', models.CharField(max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Imgupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=45)),
                ('loadway', models.FileField(upload_to=b'')),
                ('picname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=2000)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('moditime', models.DateTimeField()),
                ('keywords', models.CharField(max_length=1000)),
                ('check', models.IntegerField()),
                ('view', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('abid', models.CharField(max_length=45)),
                ('checkwords', models.CharField(max_length=2000)),
                ('nameid', models.CharField(max_length=100)),
                ('authorjob', models.CharField(max_length=200)),
                ('isdelete', models.BooleanField(default=False)),
                ('checkauthor', models.CharField(max_length=100)),
                ('protectlevel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invitecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('caninvitenum', models.IntegerField()),
                ('generateuser', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Newsbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstag', models.IntegerField()),
                ('newsstatus', models.IntegerField()),
                ('newscontent', models.CharField(max_length=200)),
                ('newsfrom', models.CharField(max_length=100)),
                ('newsfromname', models.CharField(max_length=200)),
                ('newsto', models.CharField(max_length=100)),
                ('newstoname', models.CharField(max_length=200)),
                ('isdelete', models.BooleanField(default=False)),
                ('newstime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piccollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.IntegerField()),
                ('picnum', models.CharField(max_length=200)),
                ('isdelete', models.BooleanField(default=False)),
                ('coll_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sharecollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Userallinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_sex', models.CharField(max_length=100)),
                ('user_phone', models.IntegerField(verbose_name=100)),
                ('user_info', models.CharField(max_length=1000)),
                ('user_place', models.CharField(max_length=1000)),
                ('user_nicheng', models.CharField(max_length=200)),
            ],
        ),
    ]
