# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgupload',
            name='rank',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
