# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0002_imgupload_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_feature_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=100)),
                ('img_type', models.IntegerField()),
                ('img_feature1', models.CharField(max_length=100)),
                ('img_feature2', models.CharField(max_length=100)),
                ('img_feature3', models.CharField(max_length=100)),
                ('img_feature4', models.CharField(max_length=100)),
                ('img_feature5', models.CharField(max_length=100)),
                ('img_feature6', models.CharField(max_length=100)),
                ('img_feature7', models.CharField(max_length=100)),
                ('img_feature8', models.CharField(max_length=100)),
            ],
        ),
    ]
